FROM eclipse-temurin:25-jdk-jammy

WORKDIR /workspace

COPY gradlew .
COPY gradle gradle
COPY settings.gradle.kts .
COPY build.gradle.kts .
COPY gradle.properties .

COPY api-gateway/build.gradle.kts api-gateway/build.gradle.kts
COPY catalog-service/build.gradle.kts catalog-service/build.gradle.kts
COPY discovery-server/build.gradle.kts discovery-server/build.gradle.kts

RUN chmod +x gradlew
RUN ./gradlew :catalog-service:dependencies --no-daemon

CMD ["./gradlew", ":catalog-service:bootRun", "-PskipDownload=true", "--no-daemon"]
