FROM eclipse-temurin:25-jdk-jammy

WORKDIR /workspace

COPY gradlew .
COPY gradle gradle
COPY settings.gradle.kts .
COPY build.gradle.kts .
COPY gradle.properties .

COPY api-gateway/build.gradle.kts api-gateway/build.gradle.kts
COPY catalog-service/build.gradle.kts catalog-service/build.gradle.kts
COPY discovery-server/build.gradle.kts discovery-server/build.gradle.kts
COPY customer-service/build.gradle.kts customer-service/build.gradle.kts
COPY identity-worker/build.gradle.kts identity-worker/build.gradle.kts
COPY service-comons service-comons


RUN chmod +x gradlew
RUN ./gradlew :customer-service:dependencies \
    --configuration compileClasspath \
    --no-daemon

CMD ["./gradlew", ":customer-service:bootRun", "--no-daemon"]
